include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
  exclude:
    - "**/*.g.dart"
    - "**/*.drift.dart"

linter:
  rules:
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    always_use_package_imports: true
